services:
  - type: web
    name: controle-contas-app
    env: node
    plan: free
    region: ohio
    buildCommand: npm install -g pnpm && pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: generate_a_secret_here_12345
