services:
  - type: web
    name: controle-contas-app
    env: node
    plan: starter
    region: ohio
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "22.14.0"
      - key: NODE_ENV
        value: production
      - key: LOCAL_AUTH_USERNAME
        value: "pedro"
      - key: LOCAL_AUTH_PASSWORD
        value: "pedro123"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_Qmb9LFlX0KeN@ep-weathered-glade-aqb41qeu-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
